spring.application.name=apigateway

server.port=9090

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8099/eureka
eureka.client.registry-fetch-interval-seconds=10

spring.cloud.gateway.server.webmvc.routes[0].id=route1
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://userservice
spring.cloud.gateway.server.webmvc.routes[0].predicates=Path=/service1/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=route2
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://orderservice
spring.cloud.gateway.server.webmvc.routes[1].predicates=Path=/service2/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1