spring.application.name=eurekaservice

#8761
server.port=8099


eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.client.service-url.defaultZone=http://localhost:8099/eureka

