spring.application.name=keycloakspringboot

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7079/realms/springkeycloak
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:7079/realms/springkeycloak
spring.security.oauth2.client.registration.keycloak.client-id=springclient